name: Generate Snake

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: bhumikasingh0455
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%23800080&color_dots=%23ebedf0,%239be9a8,%2340c463,%2330a14e,%23216e39
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=%23800080

      - name: Push generated files
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
